version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "rm -f /tmp/server.pid && bundle exec rails server -p 8080 -P /tmp/server.pid"
    ports:
      - 8080:8080
    volumes:
      - .:/PhotoSite
